# Generated by Django 6.0.2 on 2026-03-05 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='note',
        ),
        migrations.AddField(
            model_name='application',
            name='applicant_city',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='application',
            name='applicant_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='application',
            name='applicant_phone',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AddField(
            model_name='application',
            name='cover_note',
            field=models.TextField(blank=True, default=''),
        ),
    ]
