# Generated by Django 6.0.2 on 2026-02-22 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('plumber', 'Plumber'), ('cook', 'Cook'), ('maid', 'Maid'), ('painter', 'Painter'), ('sweeper', 'Sweeper'), ('dishwasher', 'Dishwasher'), ('electrician', 'Electrician'), ('mechanic', 'Mechanic'), ('driver', 'Driver'), ('gardener', 'Gardener')], max_length=200)),
                ('description', models.TextField(blank=True)),
                ('city', models.CharField(max_length=100)),
                ('area', models.CharField(max_length=100)),
                ('pincode', models.CharField(blank=True, max_length=6)),
                ('pay_amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('pay_type', models.CharField(choices=[('daily', 'Per Day'), ('monthly', 'Per Month'), ('hourly', 'Per Hour')], default='daily', max_length=20)),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed'), ('hired', 'Hired')], default='open', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
