# Generated by Django 6.0.2 on 2026-03-06 06:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
        ('jobs', '0002_job_posted_by_alter_job_area_alter_job_category_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='chatroom',
            unique_together={('seeker', 'recruiter')},
        ),
        migrations.AlterField(
            model_name='chatroom',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_rooms', to='jobs.job'),
        ),
    ]
